### ISSUE TITLE
代码细节

### ISSUE THREAD

**Issue by mivanzhang** [wangpeiming110/EnterAnimation#1]
作者实现了怎么多效果，着实厉害，但是代码中缺少注释，很多地方看不懂，希望作者能增加一些注解

**Comment by wangpeiming110** [comment]
多谢您的建议哈，已经加上注释并push了 (∩_∩)

> @mivanzhang

**Comment by mivanzhang** [comment]
@wangpeiming110 有没有一种方式可以不用在自定义一个viewgroup来实现这些动画？直接使用view提供的startAnimation()来做，有没有思路？

**Comment by wangpeiming110** [comment]
@mivanzhang 

听君一席话，如饮一醍醐，奈何郎才尽，穷思不得解。。。(⊙﹏⊙)

**Comment by mivanzhang** [comment]
我也是想了很久，没有想到一个合适的做法，我是一个android动画的新手，希望作者有了新的想法可以分享一下哈，拜谢

**Comment by wangpeiming110** [comment]
@mivanzhang 
好的，互相学习哈^_^
