### ISSUE TITLE
停止运行

### ISSUE THREAD

**Issue by lexinleyi** [wangpeiming110/EnterAnimation#4]
com.wangpm.enteranimation.EnterAnimLayout 这个控件加进去就停止运行，看作者写的也没有添加依赖，是不是有jar包？281815432艾特QQ，不尽感激

**Comment by wangpeiming110** [comment]
@huyitian 没有jar包哈，注意一下你工程中的EnterAnimLayout是在哪个包下的呢，因为直接copy文件进工程后，包名肯定不是com.wangpm.enteranimation这个了，需要更换包名哈
